#!/bin/bash

kubectl create secret generic cloudsql-credentials --from-env-file=secret.env --dry-run=client -o=json | kubectl apply -f -

kubectl create secret generic service-account --from-file=service-account.json --dry-run=client -o=json | kubectl apply -f -

kubectl create secret docker-registry regcred \
  --docker-server=https://us-central-docker.pkg.dev \ 
  --docker-email=rock-dev-gke-image-sa@PROJECTNAME.iam.gserviceaccount.com \
  --docker-username=_json_key \
  --docker-password="$(cat /workspace/cs.json)"

kubectl create secret aws-credentials --from-env-file=aws-secret.env --dry-run=client -o=json | kubectl apply -f -